In [1]:
import pandas as pd

df = pd.read_parquet('6번. 인코딩 및 데이터 변환.parquet')

In [2]:
normal_desc = (
    df[df['부실라벨_ICR3년'] == 0]
    .loc[:, '부채비율':]
    .describe()
    .T
)

distress_desc = (
    df[df['부실라벨_ICR3년'] == 1]
    .loc[:, '부채비율':]
    .describe()
    .T
)

In [3]:
normal_desc

,count,mean,std,min,25%,50%,75%,max
부채비율,290039.0,3143.186833,50120.778467,-6.280448e+00,59.473860,160.474716,424.560791,8.511500e+06
총부채비율,290039.0,70.917668,1927.461725,-6.701321e+00,37.293214,61.609283,80.937770,8.958000e+05
장기부채비율,290039.0,1260.837415,33686.842792,-1.400000e+03,5.007555,29.225486,129.928423,7.000000e+06
장기부채의존도,290039.0,21.308453,362.643621,-4.369432e+01,2.182326,10.308418,28.171443,1.811625e+05
차입금의존도,290039.0,44.272569,1819.274505,0.000000e+00,7.433321,33.644822,57.888680,8.958000e+05
...,...,...,...,...,...,...,...,...
영업이익률변화,290039.0,3.472344,4292.814820,-8.505929e+05,-2.537280,0.000000,1.681045,8.493585e+05
부채비율변화,290039.0,-127.555935,30413.992349,-8.441277e+06,-21.057725,0.000000,6.186240,3.448760e+06
유동비율변화,290039.0,-327.985904,55022.901137,-2.188237e+07,-17.512253,0.000000,19.043495,9.194815e+06
부실라벨_ICR3년,290039.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00
빅4감사,290039.0,0.117070,0.321505,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00

In [4]:
distress_desc

,count,mean,std,min,25%,50%,75%,max
부채비율,18003.0,8228.638006,54143.631089,0.000000e+00,180.920103,820.886981,13418.773109,5.527300e+06
총부채비율,18003.0,310.277926,9333.054908,0.000000e+00,64.402690,89.140904,108.946929,8.885500e+05
장기부채비율,18003.0,2709.737036,17344.512935,-1.612157e+00,27.478763,218.314703,4848.917466,1.400000e+06
장기부채의존도,18003.0,42.197246,779.102400,-7.978028e-01,3.088258,15.729121,45.923107,8.303333e+04
차입금의존도,18003.0,222.959319,7199.686070,0.000000e+00,35.172366,62.175325,91.047151,5.905000e+05
...,...,...,...,...,...,...,...,...
영업이익률변화,18003.0,26.698274,6430.540205,-4.082500e+05,-4.768029,0.000000,7.982971,4.226402e+05
부채비율변화,18003.0,-74.808431,47041.717853,-3.233158e+06,0.000000,0.000000,30.693266,2.005800e+06
유동비율변화,18003.0,-521.063520,56082.792104,-7.061640e+06,-25.545461,-3.774356,6.313841,1.244714e+06
부실라벨_ICR3년,18003.0,1.000000,0.000000,1.000000e+00,1.000000,1.000000,1.000000,1.000000e+00
빅4감사,18003.0,0.090207,0.286486,0.000000e+00,0.000000,0.000000,0.000000,1.000000e+00